config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#root"
  get "home", to: "pages#home"
  get "feed", to: "pages#feed"
  get "profile", to: "pages#profile"

  resources :posts do
    resources :comments, except: [:show, :index] do
      resource :vote, only: [:create]
    end
    resource :vote, only: [:create]
  end

  resources :recipes
  resources :items, except:[:new]
  resources :chats, only: [:index, :show, :destroy] do
    resources :messages, only: [:create] do
      member do
        post :save_recipe
      end
    end
  end
  resources :recipe_items, only: [:new, :create]
  resources :chat_items, only: [:new, :create]
end

app/views/shared/_comment_form.html.erb
<%= form_with(model: [post, Comment.new], local: true, class: "comment-form") do |f| %>
  <div class="comment-input-wrapper">
    <%= f.text_field :content,
        class: "comment-input",
        placeholder: "Add a comment...",
        required: true,
        autocomplete: "off" %>
    <%= f.submit "Post", class: "btn-submit-comment" %>
  </div>
<% end %>

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
  <div class="comment-item">
    <span class="comment-author">
      <%= comment.user.profile_name || comment.user.email.split('@').first %>
    </span>
    <span class="comment-text"><%= comment.content %></span>
    <span class="comment-time">
      <%= time_ago_in_words(comment.created_at) %> ago
    </span>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% flash_class = case type.to_s
      when 'notice', 'success' then 'flash-success'
      when 'alert', 'error' then 'flash-error'
      else 'flash-info'
    end %>
  <div class="flash-message <%= flash_class %>" data-controller="flash">
    <div class="flash-content">
      <span class="flash-text"><%= message %></span>
      <button type="button" class="flash-close" data-action="click->flash#close">
        <i class="bi bi-x"></i>
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% unless current_page?(home_path) || current_page?(root_path) || current_page?(new_user_session_path) || current_page?(new_user_registration_path) || current_page?(new_user_password_path) || current_page?(user_password_path) %>
  <nav class="footer navbar-light shadow-sm fixed-bottom border-top">
    <div class="container justify-content-center">
      <ul class="navbar-nav d-flex flex-row justify-content-center align-items-center gap-4 mb-0">

        <li class="foot-item">
          <%= link_to feed_path do %>
            <i class="bi bi-activity fs-1 btn rounded-5"></i>
          <% end %>
        </li>
        <li class="foot-item">
          <%= link_to chats_path do %>
            <i class="bi bi-robot fs-1 btn"></i>
          <% end %>
        </li>

        <li class="foot-item fab-container">
          <a class="fab-button"
             data-bs-toggle="offcanvas"
             href="#offcanvasAction"
             role="button"
             aria-controls="offcanvasAction">
            <% if current_page?(profile_path) %>
              <i class="bi bi-search fs-1"></i>
            <% else %>
              <i class="bi bi-plus-lg fs-1"></i>
            <% end %>
          </a>
        </li>

        <li class="foot-item">
          <%= link_to recipes_path do %>
            <i class="bi bi-book fs-1 btn"></i>
          <% end %>
        </li>
        <li class="foot-item">
          <%= link_to profile_path do %>
            <i class="bi bi-person fs-1 btn"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/shared/_navbar.html.erb
<% unless current_page?(home_path) || current_page?(root_path) || current_page?(new_user_session_path) || current_page?(new_user_registration_path) || current_page?(new_user_password_path) || current_page?(user_password_path) %>
  <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container">

      <div class="navbar-brand-container">
        <% if content_for?(:navbar_text_label)%>
          <%= link_to content_for(:navbar_text_path), class: "navbar-brand" do %>
            <%=content_for(:navbar_text_label) %>
          <% end %>
        <% end %>
        <span class="navbar-separator">|</span>
        <span class="navbar-brand-secondary">Carbodata</span>
      </div>


      <div class="ms-auto d-flex gap-2">
        <% if current_page?(profile_path) %>
          <%= link_to destroy_user_session_path,
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to log out?" },
                  class: "navbar-brand" do %>
            <span class="bi bi-box-arrow-right"></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </nav>
<% end %>